/**
 * 有根树数据模型
 * 持有节点、边、属性字段定义（schema），以及属性级显示控制。
 */
(function () {
  'use strict';
  var NS = window.AlgoCPTools;

  /**
   * @constructor
   * nodes: Map<id, { id, attributes: {name->value} }>
   * edges: Array<{ id, from, to, attributes: {name->value} }>
   * nodeAttributeFields / edgeAttributeFields: Array<{ name, visible, autoGenerated }>
   */
  function TreeModel() {
    this.root = null;
    this.nodes = new Map();
    this.edges = [];
    this.nodeAttributeFields = [];
    this.edgeAttributeFields = [];
    this._nextEdgeId = 1;
  }

  TreeModel.prototype.reset = function () {
    this.root = null;
    this.nodes = new Map();
    this.edges = [];
    this.nodeAttributeFields = [];
    this.edgeAttributeFields = [];
    this._nextEdgeId = 1;
  };

  TreeModel.prototype.addNode = function (id) {
    if (!this.nodes.has(id)) {
      this.nodes.set(id, { id: id, attributes: {} });
    }
    return this.nodes.get(id);
  };

  TreeModel.prototype.addEdge = function (from, to) {
    var edge = { id: this._nextEdgeId++, from: from, to: to, attributes: {} };
    this.edges.push(edge);
    return edge;
  };

  /** 自动生成 id 字段并填充每个节点/边的 id 属性值。 */
  TreeModel.prototype.ensureIdFields = function () {
    if (!this.nodeAttributeFields.some(function (f) { return f.name === 'id'; })) {
      this.nodeAttributeFields.unshift({ name: 'id', visible: false, autoGenerated: true });
    }
    if (!this.edgeAttributeFields.some(function (f) { return f.name === 'id'; })) {
      this.edgeAttributeFields.unshift({ name: 'id', visible: false, autoGenerated: true });
    }
    this.nodes.forEach(function (node) { node.attributes.id = String(node.id); });
    this.edges.forEach(function (edge) { edge.attributes.id = String(edge.id); });
  };

  TreeModel.prototype.addNodeField = function (name) {
    if (!name || this.nodeAttributeFields.some(function (f) { return f.name === name; })) return;
    this.nodeAttributeFields.push({ name: name, visible: true, autoGenerated: false });
    this.nodes.forEach(function (node) {
      if (node.attributes[name] === undefined) node.attributes[name] = '';
    });
  };

  TreeModel.prototype.addEdgeField = function (name) {
    if (!name || this.edgeAttributeFields.some(function (f) { return f.name === name; })) return;
    this.edgeAttributeFields.push({ name: name, visible: true, autoGenerated: false });
    this.edges.forEach(function (edge) {
      if (edge.attributes[name] === undefined) edge.attributes[name] = '';
    });
  };

  TreeModel.prototype.removeNodeField = function (name) {
    if (name === 'id') return; // 自动 id 不可删除
    this.nodeAttributeFields = this.nodeAttributeFields.filter(function (f) { return f.name !== name; });
    this.nodes.forEach(function (node) { delete node.attributes[name]; });
  };

  TreeModel.prototype.removeEdgeField = function (name) {
    if (name === 'id') return;
    this.edgeAttributeFields = this.edgeAttributeFields.filter(function (f) { return f.name !== name; });
    this.edges.forEach(function (edge) { delete edge.attributes[name]; });
  };

  TreeModel.prototype.setNodeFieldVisible = function (name, visible) {
    var f = this.nodeAttributeFields.find(function (f) { return f.name === name; });
    if (f) f.visible = visible;
  };

  TreeModel.prototype.setEdgeFieldVisible = function (name, visible) {
    var f = this.edgeAttributeFields.find(function (f) { return f.name === name; });
    if (f) f.visible = visible;
  };

  /**
   * 返回节点标签字符串，格式：`${id}: ${attr1}, ${attr2}`。
   * id 始终作为前缀，后接可见非 id 属性的值（逗号分隔）。
   */
  TreeModel.prototype.getNodeLabel = function (nodeId) {
    var node = this.nodes.get(nodeId);
    if (!node) return String(nodeId);
    var values = [];
    this.nodeAttributeFields.forEach(function (f) {
      if (f.name === 'id') return; // id 作为前缀，不重复列出
      if (!f.visible) return;
      var v = node.attributes[f.name];
      if (v === undefined || v === '') return;
      values.push(v);
    });
    if (values.length === 0) return String(nodeId);
    return nodeId + ': ' + values.join(', ');
  };

  /**
   * 返回边标签字符串。
   * id 字段可见时格式：`${id}: ${attr1}, ${attr2}`；不可见时仅显示属性值。
   * 无可见属性时返回空字符串。
   */
  TreeModel.prototype.getEdgeLabel = function (edge) {
    var idField = this.edgeAttributeFields.find(function (f) { return f.name === 'id'; });
    var showId = !idField || idField.visible;
    var values = [];
    this.edgeAttributeFields.forEach(function (f) {
      if (f.name === 'id') return;
      if (!f.visible) return;
      var v = edge.attributes[f.name];
      if (v === undefined || v === '') return;
      values.push(v);
    });
    if (values.length === 0) return '';
    if (showId) return edge.id + ': ' + values.join(', ');
    return values.join(', ');
  };

  /** 由边集构建 children 映射，按节点 id 升序排列，供布局使用。 */
  TreeModel.prototype.getChildrenMap = function () {
    var map = {};
    this.nodes.forEach(function (n) { map[n.id] = []; });
    this.edges.forEach(function (e) {
      if (!map[e.from]) map[e.from] = [];
      map[e.from].push(e.to);
    });
    Object.keys(map).forEach(function (k) {
      map[k].sort(function (a, b) { return Number(a) - Number(b); });
    });
    return map;
  };

  TreeModel.prototype.getAllNodeIds = function () {
    var ids = [];
    this.nodes.forEach(function (n) { ids.push(n.id); });
    return ids;
  };

  NS.models.TreeModel = TreeModel;
})();
